import React from 'react';
import { Quote, RefreshCw } from 'lucide-react';
import { useQuote } from '../contexts/QuoteContext';

const QuoteSection = () => {
  const { quote, author, isLoading, refreshQuote } = useQuote();

  return (
    <section className="py-20 bg-gradient-to-r from-gray-100 via-gray-50 to-gray-100 relative overflow-hidden">
      {/* Background decoration */}
      <div className="absolute inset-0">
        <div className="absolute top-10 left-10 w-32 h-32 bg-gray-200 rounded-full opacity-30 animate-float"></div>
        <div className="absolute bottom-10 right-10 w-24 h-24 bg-gray-300 rounded-full opacity-40 animate-float animation-delay-2000"></div>
      </div>

      <div className="container mx-auto px-6 relative z-10">
        <div className="max-w-4xl mx-auto text-center">
          {/* Quote Icon */}
          <div className="inline-flex items-center justify-center w-16 h-16 bg-gradient-to-r from-gray-600 to-gray-800 rounded-full mb-6 shadow-lg">
            <Quote className="text-white" size={28} />
          </div>

          {/* Quote Display */}
          <div className="space-y-6">
            {isLoading ? (
              <div className="flex flex-col items-center space-y-4">
                <div className="w-8 h-8 border-3 border-gray-300 border-t-gray-600 rounded-full animate-spin"></div>
                <p className="text-gray-500">Loading inspiration...</p>
              </div>
            ) : (
              <>
                <blockquote className="text-2xl md:text-3xl text-gray-800 leading-relaxed italic font-medium">
                  "{quote}"
                </blockquote>
                <cite className="text-gray-600 font-semibold text-lg">
                  — {author}
                </cite>
              </>
            )}

            <br />

            {/* Refresh Button */}
            <button
              onClick={refreshQuote}
              disabled={isLoading}
              className="inline-flex items-center space-x-2 bg-gray-800 text-white px-6 py-3 rounded-full font-semibold hover:bg-gray-700 transition-all duration-200 hover:scale-105 disabled:opacity-50 disabled:cursor-not-allowed"
            >
              <RefreshCw size={18} className={isLoading ? 'animate-spin' : ''} />
              <span>New Inspiration</span>
            </button>

            <p className="text-s text-gray-800 text-center mt-4 relative z-10">
              💡 Quote generated by AI (GPT 3.5 Turbo Model)
            </p>
          </div>
        </div>
      </div>
    </section>
  );
};

export default QuoteSection;